export const questionBank: { [key: string]: any[] } = {
  HTML: [
    {
      id: 1,
      question: "What does HTML stand for?",
      options: [
        "HyperText Markup Language",
        "High Tech Modern Language",
        "Home Tool Markup Language",
        "Hyperlink and Text Markup Language",
      ],
      correctAnswer: 0,
    },
    {
      id: 2,
      question: "Which HTML element is used for the largest heading?",
      options: ["<h6>", "<h1>", "<heading>", "<header>"],
      correctAnswer: 1,
    },
    {
      id: 3,
      question: "What is the correct HTML element for inserting a line break?",
      options: ["<break>", "<lb>", "<br>", "<newline>"],
      correctAnswer: 2,
    },
    {
      id: 4,
      question: "Which attribute is used to specify the URL of a link?",
      options: ["src", "href", "link", "url"],
      correctAnswer: 1,
    },
    {
      id: 5,
      question: "What is the correct HTML for creating a hyperlink?",
      options: [
        "<a url='http://example.com'>Example</a>",
        "<a href='http://example.com'>Example</a>",
        "<a>http://example.com</a>",
        "<link>http://example.com</link>",
      ],
      correctAnswer: 1,
    },
    {
      id: 6,
      question: "Which HTML element defines the title of a document?",
      options: ["<meta>", "<title>", "<head>", "<header>"],
      correctAnswer: 1,
    },
    {
      id: 7,
      question: "What is the correct HTML for making a checkbox?",
      options: ["<input type='check'>", "<input type='checkbox'>", "<checkbox>", "<check>"],
      correctAnswer: 1,
    },
    {
      id: 8,
      question: "Which HTML element is used to specify a footer for a document?",
      options: ["<bottom>", "<section>", "<footer>", "<foot>"],
      correctAnswer: 2,
    },
    {
      id: 9,
      question: "What is the correct HTML for inserting an image?",
      options: [
        "<img href='image.gif' alt='MyImage'>",
        "<img src='image.gif' alt='MyImage'>",
        "<image src='image.gif' alt='MyImage'>",
        "<img alt='MyImage'>image.gif</img>",
      ],
      correctAnswer: 1,
    },
    {
      id: 10,
      question: "Which HTML attribute specifies an alternate text for an image?",
      options: ["title", "alt", "src", "longdesc"],
      correctAnswer: 1,
    },
    {
      id: 11,
      question: "What is the correct HTML for making a text input field?",
      options: ["<input type='text'>", "<textfield>", "<input type='textfield'>", "<textinput type='text'>"],
      correctAnswer: 0,
    },
    {
      id: 12,
      question: "Which HTML element defines navigation links?",
      options: ["<navigation>", "<navigate>", "<nav>", "<navlink>"],
      correctAnswer: 2,
    },
    {
      id: 13,
      question: "What is the correct HTML for making a drop-down list?",
      options: ["<input type='dropdown'>", "<select>", "<input type='list'>", "<dropdown>"],
      correctAnswer: 1,
    },
    {
      id: 14,
      question: "Which HTML element is used to display a scalar value within a range?",
      options: ["<gauge>", "<meter>", "<measure>", "<range>"],
      correctAnswer: 1,
    },
    {
      id: 15,
      question: "What is the correct HTML for making a text area?",
      options: ["<input type='textarea'>", "<textarea>", "<input type='textbox'>", "<textbox>"],
      correctAnswer: 1,
    },
    {
      id: 16,
      question: "Which HTML element defines a table header?",
      options: ["<thead>", "<th>", "<header>", "<head>"],
      correctAnswer: 1,
    },
    {
      id: 17,
      question: "What is the correct HTML for inserting a background image?",
      options: [
        "<body bg='background.gif'>",
        "<body style='background-image:url(background.gif)'>",
        "<background img='background.gif'>",
        "<body background='background.gif'>",
      ],
      correctAnswer: 1,
    },
    {
      id: 18,
      question: "Which HTML element is used to group related form elements?",
      options: ["<group>", "<fieldset>", "<form-group>", "<section>"],
      correctAnswer: 1,
    },
    {
      id: 19,
      question: "What is the correct HTML for creating an ordered list?",
      options: ["<ul>", "<ol>", "<list>", "<order>"],
      correctAnswer: 1,
    },
    {
      id: 20,
      question: "Which HTML attribute is used to define inline styles?",
      options: ["class", "style", "styles", "font"],
      correctAnswer: 1,
    },
    {
      id: 21,
      question: "What does the HTML <canvas> element do?",
      options: ["Creates a container for graphics", "Displays images", "Creates forms", "Defines navigation"],
      correctAnswer: 0,
    },
    {
      id: 22,
      question: "Which HTML element represents a section of a page that links to other pages?",
      options: ["<nav>", "<section>", "<aside>", "<article>"],
      correctAnswer: 0,
    },
    {
      id: 23,
      question: "What is the purpose of the HTML <meta> tag?",
      options: ["To create metadata about the HTML document", "To create links", "To insert images", "To create forms"],
      correctAnswer: 0,
    },
    {
      id: 24,
      question: "Which HTML element is used for emphasized text?",
      options: ["<italic>", "<i>", "<em>", "<emphasis>"],
      correctAnswer: 2,
    },
    {
      id: 25,
      question: "What is the correct HTML for making text bold?",
      options: ["<bold>", "<b>", "<strong>", "Both <b> and <strong>"],
      correctAnswer: 3,
    },
  ],
  CSS: [
    {
      id: 1,
      question: "What does CSS stand for?",
      options: ["Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"],
      correctAnswer: 1,
    },
    {
      id: 2,
      question: "Which HTML attribute is used to define inline styles?",
      options: ["class", "style", "styles", "font"],
      correctAnswer: 1,
    },
    {
      id: 3,
      question: "Which is the correct CSS syntax?",
      options: ["body:color=black;", "{body;color:black;}", "body {color: black;}", "{body:color=black;}"],
      correctAnswer: 2,
    },
    {
      id: 4,
      question: "How do you insert a comment in a CSS file?",
      options: ["// this is a comment", "/* this is a comment */", "' this is a comment", "// this is a comment //"],
      correctAnswer: 1,
    },
    {
      id: 5,
      question: "Which property is used to change the background color?",
      options: ["color", "bgcolor", "background-color", "background"],
      correctAnswer: 2,
    },
    {
      id: 6,
      question: "How do you add a background color for all <h1> elements?",
      options: [
        "all.h1 {background-color:#FFFFFF;}",
        "h1.all {background-color:#FFFFFF;}",
        "h1 {background-color:#FFFFFF;}",
        "h1 {bgcolor:#FFFFFF;}",
      ],
      correctAnswer: 2,
    },
    {
      id: 7,
      question: "Which CSS property is used to change the text color of an element?",
      options: ["fgcolor", "color", "text-color", "font-color"],
      correctAnswer: 1,
    },
    {
      id: 8,
      question: "Which CSS property controls the text size?",
      options: ["text-style", "font-size", "text-size", "font-style"],
      correctAnswer: 1,
    },
    {
      id: 9,
      question: "What is the correct CSS syntax for making all the <p> elements bold?",
      options: ["p {text-size:bold;}", "p {font-weight:bold;}", "<p style='font-size:bold;'>", "p {text-weight:bold;}"],
      correctAnswer: 1,
    },
    {
      id: 10,
      question: "How do you display hyperlinks without an underline?",
      options: [
        "a {underline:none;}",
        "a {text-decoration:no-underline;}",
        "a {decoration:no-underline;}",
        "a {text-decoration:none;}",
      ],
      correctAnswer: 3,
    },
    {
      id: 11,
      question: "Which property is used to change the font of an element?",
      options: ["font-family", "font-weight", "font-style", "font"],
      correctAnswer: 0,
    },
    {
      id: 12,
      question: "How do you make each word in a text start with a capital letter?",
      options: ["text-transform:capitalize", "text-style:capitalize", "transform:capitalize", "text-capitalize:true"],
      correctAnswer: 0,
    },
    {
      id: 13,
      question: "Which property is used to change the left margin of an element?",
      options: ["padding-left", "margin-left", "indent", "left-margin"],
      correctAnswer: 1,
    },
    {
      id: 14,
      question: "What is the correct way to select an element with id 'demo'?",
      options: ["demo", ".demo", "#demo", "*demo"],
      correctAnswer: 2,
    },
    {
      id: 15,
      question: "What is the correct way to select elements with class name 'test'?",
      options: [".test", "#test", "test", "*test"],
      correctAnswer: 0,
    },
    {
      id: 16,
      question: "Which CSS property is used to make text italic?",
      options: ["font-style", "text-style", "font-weight", "text-decoration"],
      correctAnswer: 0,
    },
    {
      id: 17,
      question: "How do you center-align text?",
      options: ["text-align:center", "align:center", "text-center:true", "center-align:true"],
      correctAnswer: 0,
    },
    {
      id: 18,
      question: "Which CSS property is used to set the spacing between lines of text?",
      options: ["line-height", "text-spacing", "line-spacing", "text-height"],
      correctAnswer: 0,
    },
    {
      id: 19,
      question: "What is the default value of the position property?",
      options: ["relative", "fixed", "absolute", "static"],
      correctAnswer: 3,
    },
    {
      id: 20,
      question: "Which CSS property is used to create space around elements?",
      options: ["spacing", "margin", "padding", "border"],
      correctAnswer: 1,
    },
    {
      id: 21,
      question: "How do you make a list that lists its items with squares?",
      options: ["list-style-type: square", "list-type: square", "list: square", "list-style: square"],
      correctAnswer: 0,
    },
    {
      id: 22,
      question: "Which CSS property is used to control the stacking order of elements?",
      options: ["z-index", "stack-order", "layer", "depth"],
      correctAnswer: 0,
    },
    {
      id: 23,
      question: "What does the CSS box model consist of?",
      options: [
        "Content, padding, border, margin",
        "Content, spacing, border, outline",
        "Text, padding, border, margin",
        "Content, padding, outline, margin",
      ],
      correctAnswer: 0,
    },
    {
      id: 24,
      question: "Which CSS property is used to make elements invisible?",
      options: ["display: none", "visibility: hidden", "opacity: 0", "All of the above"],
      correctAnswer: 3,
    },
    {
      id: 25,
      question: "What is the CSS property used to create rounded corners?",
      options: ["corner-radius", "border-radius", "round-corner", "border-round"],
      correctAnswer: 1,
    },
  ],
  PYTHON: [
    {
      id: 1,
      question: "What is the correct way to create a function in Python?",
      options: ["function myFunction():", "def myFunction():", "create myFunction():", "func myFunction():"],
      correctAnswer: 1,
    },
    {
      id: 2,
      question: "Which of the following is used to define a class in Python?",
      options: ["class", "Class", "define", "def"],
      correctAnswer: 0,
    },
    {
      id: 3,
      question: "What is the output of print(2 ** 3)?",
      options: ["6", "8", "9", "23"],
      correctAnswer: 1,
    },
    {
      id: 4,
      question: "Which method is used to add an element to a list?",
      options: ["add()", "append()", "insert()", "push()"],
      correctAnswer: 1,
    },
    {
      id: 5,
      question: "What is the correct way to create a dictionary in Python?",
      options: ["dict = {key: value}", "dict = [key: value]", "dict = (key: value)", "dict = <key: value>"],
      correctAnswer: 0,
    },
    {
      id: 6,
      question: "Which of the following is NOT a Python data type?",
      options: ["int", "float", "boolean", "char"],
      correctAnswer: 3,
    },
    {
      id: 7,
      question: "What does the len() function do?",
      options: [
        "Returns the length of an object",
        "Returns the last element",
        "Returns the first element",
        "Returns the type of object",
      ],
      correctAnswer: 0,
    },
    {
      id: 8,
      question: "Which operator is used for floor division in Python?",
      options: ["/", "//", "%", "**"],
      correctAnswer: 1,
    },
    {
      id: 9,
      question: "What is the correct way to handle exceptions in Python?",
      options: ["try-catch", "try-except", "try-finally", "catch-except"],
      correctAnswer: 1,
    },
    {
      id: 10,
      question: "Which method is used to remove an item from a list?",
      options: ["delete()", "remove()", "pop()", "Both remove() and pop()"],
      correctAnswer: 3,
    },
    {
      id: 11,
      question: "What is the output of print('Hello' + 'World')?",
      options: ["Hello World", "HelloWorld", "Hello+World", "Error"],
      correctAnswer: 1,
    },
    {
      id: 12,
      question: "Which keyword is used to create a loop in Python?",
      options: ["loop", "for", "repeat", "iterate"],
      correctAnswer: 1,
    },
    {
      id: 13,
      question: "What is the correct way to import a module in Python?",
      options: ["include module", "import module", "using module", "require module"],
      correctAnswer: 1,
    },
    {
      id: 14,
      question: "Which of the following is used to create a comment in Python?",
      options: ["//", "/*", "#", "<!--"],
      correctAnswer: 2,
    },
    {
      id: 15,
      question: "What is the correct way to create a string in Python?",
      options: ["str = 'Hello'", 'str = "Hello"', "str = '''Hello'''", "All of the above"],
      correctAnswer: 3,
    },
    {
      id: 16,
      question: "Which method is used to convert a string to uppercase?",
      options: ["upper()", "toUpper()", "uppercase()", "UPPER()"],
      correctAnswer: 0,
    },
    {
      id: 17,
      question: "What is the output of print(type(5.0))?",
      options: ["<class 'int'>", "<class 'float'>", "<class 'double'>", "<class 'number'>"],
      correctAnswer: 1,
    },
    {
      id: 18,
      question: "Which of the following is used to create an empty list?",
      options: ["list = []", "list = list()", "list = {}", "Both A and B"],
      correctAnswer: 3,
    },
    {
      id: 19,
      question: "What is the correct way to create a tuple?",
      options: ["tuple = (1, 2, 3)", "tuple = [1, 2, 3]", "tuple = {1, 2, 3}", "tuple = <1, 2, 3>"],
      correctAnswer: 0,
    },
    {
      id: 20,
      question: "Which keyword is used to define a class method that doesn't need an instance?",
      options: ["@classmethod", "@staticmethod", "@property", "@method"],
      correctAnswer: 1,
    },
    {
      id: 21,
      question: "What is inheritance in Python?",
      options: [
        "A way to create new classes based on existing classes",
        "A way to hide data",
        "A way to create functions",
        "A way to import modules",
      ],
      correctAnswer: 0,
    },
    {
      id: 22,
      question: "Which method is called when an object is created?",
      options: ["__init__", "__new__", "__create__", "__start__"],
      correctAnswer: 0,
    },
    {
      id: 23,
      question: "What is polymorphism in Python?",
      options: [
        "Having multiple forms",
        "Using the same interface for different data types",
        "Creating multiple classes",
        "Hiding implementation details",
      ],
      correctAnswer: 1,
    },
    {
      id: 24,
      question: "Which of the following is an example of encapsulation?",
      options: ["Using private variables", "Creating classes", "Using inheritance", "Creating functions"],
      correctAnswer: 0,
    },
    {
      id: 25,
      question: "What does the super() function do?",
      options: ["Creates a superclass", "Calls the parent class method", "Creates a super variable", "Deletes a class"],
      correctAnswer: 1,
    },
  ],
  JAVA: [
    {
      id: 1,
      question: "Which of the following is the correct way to declare a variable in Java?",
      options: ["int x;", "variable int x;", "declare int x;", "int declare x;"],
      correctAnswer: 0,
    },
    {
      id: 2,
      question: "What is the main method signature in Java?",
      options: [
        "public static void main(String args[])",
        "public void main(String args[])",
        "static void main(String args[])",
        "void main(String args[])",
      ],
      correctAnswer: 0,
    },
    {
      id: 3,
      question: "Which keyword is used to create a class in Java?",
      options: ["class", "Class", "create", "new"],
      correctAnswer: 0,
    },
    {
      id: 4,
      question: "What is inheritance in Java?",
      options: [
        "A mechanism where one class acquires properties of another class",
        "A way to hide data",
        "A way to create objects",
        "A way to define methods",
      ],
      correctAnswer: 0,
    },
    {
      id: 5,
      question: "Which keyword is used to inherit a class in Java?",
      options: ["inherits", "extends", "implements", "super"],
      correctAnswer: 1,
    },
    {
      id: 6,
      question: "What is encapsulation in Java?",
      options: [
        "Wrapping data and methods into a single unit",
        "Creating multiple classes",
        "Using inheritance",
        "Creating interfaces",
      ],
      correctAnswer: 0,
    },
    {
      id: 7,
      question: "Which access modifier makes a member accessible only within the same class?",
      options: ["public", "private", "protected", "default"],
      correctAnswer: 1,
    },
    {
      id: 8,
      question: "What is polymorphism in Java?",
      options: [
        "Having multiple forms",
        "One interface, multiple implementations",
        "Creating multiple classes",
        "Using inheritance",
      ],
      correctAnswer: 1,
    },
    {
      id: 9,
      question: "Which keyword is used to create an object in Java?",
      options: ["create", "new", "object", "instance"],
      correctAnswer: 1,
    },
    {
      id: 10,
      question: "What is method overloading?",
      options: [
        "Having multiple methods with the same name but different parameters",
        "Overriding parent class methods",
        "Creating abstract methods",
        "Using static methods",
      ],
      correctAnswer: 0,
    },
    {
      id: 11,
      question: "What is method overriding?",
      options: [
        "Creating new methods",
        "Redefining parent class methods in child class",
        "Using static methods",
        "Creating abstract methods",
      ],
      correctAnswer: 1,
    },
    {
      id: 12,
      question: "Which keyword is used to prevent inheritance?",
      options: ["static", "final", "abstract", "private"],
      correctAnswer: 1,
    },
    {
      id: 13,
      question: "What is an abstract class?",
      options: [
        "A class that cannot be instantiated",
        "A class with only static methods",
        "A class with private methods",
        "A class with final methods",
      ],
      correctAnswer: 0,
    },
    {
      id: 14,
      question: "What is an interface in Java?",
      options: [
        "A contract that classes must follow",
        "A type of class",
        "A way to create objects",
        "A method definition",
      ],
      correctAnswer: 0,
    },
    {
      id: 15,
      question: "Which keyword is used to implement an interface?",
      options: ["extends", "implements", "inherits", "uses"],
      correctAnswer: 1,
    },
    {
      id: 16,
      question: "What is a constructor in Java?",
      options: [
        "A special method used to initialize objects",
        "A method to destroy objects",
        "A static method",
        "A final method",
      ],
      correctAnswer: 0,
    },
    {
      id: 17,
      question: "Which of the following is NOT a primitive data type in Java?",
      options: ["int", "float", "String", "boolean"],
      correctAnswer: 2,
    },
    {
      id: 18,
      question: "What is the difference between == and .equals() in Java?",
      options: [
        "== compares references, .equals() compares content",
        "== compares content, .equals() compares references",
        "Both are the same",
        "== is for primitives, .equals() is for objects",
      ],
      correctAnswer: 0,
    },
    {
      id: 19,
      question: "What is the super keyword used for?",
      options: [
        "To call parent class methods and constructors",
        "To create objects",
        "To define static methods",
        "To create interfaces",
      ],
      correctAnswer: 0,
    },
    {
      id: 20,
      question: "What is the this keyword used for?",
      options: [
        "To refer to the current object",
        "To create new objects",
        "To call static methods",
        "To define classes",
      ],
      correctAnswer: 0,
    },
    {
      id: 21,
      question: "What is a static method?",
      options: [
        "A method that belongs to the class rather than instance",
        "A method that cannot be overridden",
        "A method that is private",
        "A method that is final",
      ],
      correctAnswer: 0,
    },
    {
      id: 22,
      question: "What is garbage collection in Java?",
      options: ["Automatic memory management", "Manual memory management", "Error handling", "Exception handling"],
      correctAnswer: 0,
    },
    {
      id: 23,
      question: "Which exception is thrown when dividing by zero?",
      options: ["NullPointerException", "ArithmeticException", "NumberFormatException", "IllegalArgumentException"],
      correctAnswer: 1,
    },
    {
      id: 24,
      question: "What is the purpose of the finally block?",
      options: [
        "Code that always executes regardless of exceptions",
        "Code that executes only when exception occurs",
        "Code that executes only when no exception occurs",
        "Code that handles specific exceptions",
      ],
      correctAnswer: 0,
    },
    {
      id: 25,
      question: "What is multithreading in Java?",
      options: [
        "Executing multiple threads concurrently",
        "Creating multiple classes",
        "Using multiple inheritance",
        "Creating multiple objects",
      ],
      correctAnswer: 0,
    },
  ],
  C: [
    {
      id: 1,
      question: "Who developed the C programming language?",
      options: ["Dennis Ritchie", "Ken Thompson", "Brian Kernighan", "Bjarne Stroustrup"],
      correctAnswer: 0,
    },
    {
      id: 2,
      question: "Which header file is required for input/output functions?",
      options: ["<iostream>", "<stdio.h>", "<conio.h>", "<stdlib.h>"],
      correctAnswer: 1,
    },
    {
      id: 3,
      question: "What is the correct way to declare a pointer in C?",
      options: ["int ptr;", "int *ptr;", "int &ptr;", "pointer int ptr;"],
      correctAnswer: 1,
    },
    {
      id: 4,
      question: "Which function is used to allocate memory dynamically?",
      options: ["alloc()", "malloc()", "calloc()", "Both malloc() and calloc()"],
      correctAnswer: 3,
    },
    {
      id: 5,
      question: "What is the size of int data type in C (typically)?",
      options: ["2 bytes", "4 bytes", "8 bytes", "Depends on system"],
      correctAnswer: 3,
    },
    {
      id: 6,
      question: "Which operator is used to get the address of a variable?",
      options: ["*", "&", "@", "#"],
      correctAnswer: 1,
    },
    {
      id: 7,
      question: "What is the correct syntax for a for loop in C?",
      options: [
        "for(initialization; condition; increment)",
        "for(condition; initialization; increment)",
        "for(increment; condition; initialization)",
        "for(initialization; increment; condition)",
      ],
      correctAnswer: 0,
    },
    {
      id: 8,
      question: "Which function is used to free dynamically allocated memory?",
      options: ["delete()", "free()", "dealloc()", "remove()"],
      correctAnswer: 1,
    },
    {
      id: 9,
      question: "What is a structure in C?",
      options: [
        "A collection of variables of different data types",
        "A collection of variables of same data type",
        "A function",
        "A pointer",
      ],
      correctAnswer: 0,
    },
    {
      id: 10,
      question: "Which keyword is used to define a structure?",
      options: ["struct", "structure", "class", "define"],
      correctAnswer: 0,
    },
    {
      id: 11,
      question: "What is the difference between array and pointer?",
      options: [
        "Array is a collection, pointer stores address",
        "Array and pointer are same",
        "Array stores address, pointer is collection",
        "No difference",
      ],
      correctAnswer: 0,
    },
    {
      id: 12,
      question: "Which function is used to copy strings in C?",
      options: ["copy()", "strcpy()", "stringcopy()", "strdup()"],
      correctAnswer: 1,
    },
    {
      id: 13,
      question: "What is the return type of main() function?",
      options: ["void", "int", "char", "float"],
      correctAnswer: 1,
    },
    {
      id: 14,
      question: "Which preprocessor directive is used to include header files?",
      options: ["#include", "#define", "#ifdef", "#import"],
      correctAnswer: 0,
    },
    {
      id: 15,
      question: "What is recursion in C?",
      options: ["A function calling itself", "A loop", "A conditional statement", "A data type"],
      correctAnswer: 0,
    },
    {
      id: 16,
      question: "Which storage class has the longest lifetime?",
      options: ["auto", "static", "register", "extern"],
      correctAnswer: 1,
    },
    {
      id: 17,
      question: "What is the purpose of break statement?",
      options: ["To exit from loop or switch", "To continue loop", "To return from function", "To define variables"],
      correctAnswer: 0,
    },
    {
      id: 18,
      question: "Which operator has the highest precedence?",
      options: ["*", "+", "()", "="],
      correctAnswer: 2,
    },
    {
      id: 19,
      question: "What is a union in C?",
      options: ["Similar to structure but shares memory", "Same as structure", "A type of array", "A function"],
      correctAnswer: 0,
    },
    {
      id: 20,
      question: "Which function is used to find string length?",
      options: ["length()", "strlen()", "size()", "count()"],
      correctAnswer: 1,
    },
    {
      id: 21,
      question: "What is the purpose of continue statement?",
      options: [
        "To skip current iteration and continue with next",
        "To exit from loop",
        "To return from function",
        "To break the program",
      ],
      correctAnswer: 0,
    },
    {
      id: 22,
      question: "Which function is used to compare strings?",
      options: ["compare()", "strcmp()", "stringcompare()", "strcomp()"],
      correctAnswer: 1,
    },
    {
      id: 23,
      question: "What is a macro in C?",
      options: ["A preprocessor directive that defines constants or functions", "A variable", "A data type", "A loop"],
      correctAnswer: 0,
    },
    {
      id: 24,
      question: "Which header file contains mathematical functions?",
      options: ["<stdio.h>", "<math.h>", "<stdlib.h>", "<string.h>"],
      correctAnswer: 1,
    },
    {
      id: 25,
      question: "What is the difference between call by value and call by reference?",
      options: [
        "Call by value passes copy, call by reference passes address",
        "Both are same",
        "Call by value passes address, call by reference passes copy",
        "No difference",
      ],
      correctAnswer: 0,
    },
  ],
  "C++": [
    {
      id: 1,
      question: "Who developed C++?",
      options: ["Dennis Ritchie", "Bjarne Stroustrup", "Ken Thompson", "James Gosling"],
      correctAnswer: 1,
    },
    {
      id: 2,
      question: "What is the main difference between C and C++?",
      options: ["C++ supports object-oriented programming", "C++ is faster", "C++ has better syntax", "No difference"],
      correctAnswer: 0,
    },
    {
      id: 3,
      question: "Which keyword is used to define a class in C++?",
      options: ["class", "Class", "struct", "object"],
      correctAnswer: 0,
    },
    {
      id: 4,
      question: "What is encapsulation in C++?",
      options: [
        "Wrapping data and functions together",
        "Creating multiple classes",
        "Using inheritance",
        "Creating objects",
      ],
      correctAnswer: 0,
    },
    {
      id: 5,
      question: "Which access specifier makes members accessible only within the class?",
      options: ["public", "private", "protected", "friend"],
      correctAnswer: 1,
    },
    {
      id: 6,
      question: "What is inheritance in C++?",
      options: [
        "A mechanism to create new classes from existing classes",
        "Creating objects",
        "Defining functions",
        "Using pointers",
      ],
      correctAnswer: 0,
    },
    {
      id: 7,
      question: "Which operator is used for dynamic memory allocation in C++?",
      options: ["malloc", "new", "alloc", "create"],
      correctAnswer: 1,
    },
    {
      id: 8,
      question: "What is polymorphism in C++?",
      options: [
        "One interface, multiple implementations",
        "Creating multiple classes",
        "Using inheritance",
        "Defining functions",
      ],
      correctAnswer: 0,
    },
    {
      id: 9,
      question: "Which keyword is used to inherit a class?",
      options: ["inherits", "extends", ":", "->"],
      correctAnswer: 2,
    },
    {
      id: 10,
      question: "What is a constructor in C++?",
      options: [
        "A special function to initialize objects",
        "A function to destroy objects",
        "A static function",
        "A virtual function",
      ],
      correctAnswer: 0,
    },
    {
      id: 11,
      question: "What is a destructor in C++?",
      options: [
        "A function to clean up when object is destroyed",
        "A function to create objects",
        "A static function",
        "A virtual function",
      ],
      correctAnswer: 0,
    },
    {
      id: 12,
      question: "Which symbol is used to define a destructor?",
      options: ["~", "@", "#", "&"],
      correctAnswer: 0,
    },
    {
      id: 13,
      question: "What is function overloading?",
      options: [
        "Multiple functions with same name but different parameters",
        "Redefining base class functions",
        "Creating virtual functions",
        "Using static functions",
      ],
      correctAnswer: 0,
    },
    {
      id: 14,
      question: "What is operator overloading?",
      options: [
        "Giving additional meanings to operators",
        "Creating new operators",
        "Using multiple operators",
        "Defining functions",
      ],
      correctAnswer: 0,
    },
    {
      id: 15,
      question: "Which keyword is used for function overriding?",
      options: ["virtual", "override", "static", "const"],
      correctAnswer: 0,
    },
    {
      id: 16,
      question: "What is an abstract class in C++?",
      options: [
        "A class with at least one pure virtual function",
        "A class with only static functions",
        "A class with private members",
        "A class with constructors",
      ],
      correctAnswer: 0,
    },
    {
      id: 17,
      question: "How do you declare a pure virtual function?",
      options: [
        "virtual function() = 0;",
        "pure virtual function();",
        "abstract function();",
        "virtual function() abstract;",
      ],
      correctAnswer: 0,
    },
    {
      id: 18,
      question: "What is multiple inheritance?",
      options: [
        "A class inheriting from multiple base classes",
        "Multiple classes inheriting from one base class",
        "Creating multiple objects",
        "Using multiple functions",
      ],
      correctAnswer: 0,
    },
    {
      id: 19,
      question: "Which header file is required for input/output in C++?",
      options: ["<stdio.h>", "<iostream>", "<conio.h>", "<fstream>"],
      correctAnswer: 1,
    },
    {
      id: 20,
      question: "What is the scope resolution operator in C++?",
      options: ["::", "->", ".", "&"],
      correctAnswer: 0,
    },
    {
      id: 21,
      question: "What is a friend function?",
      options: [
        "A function that can access private members of a class",
        "A public function",
        "A static function",
        "A virtual function",
      ],
      correctAnswer: 0,
    },
    {
      id: 22,
      question: "What is the this pointer?",
      options: [
        "A pointer that points to the current object",
        "A pointer to base class",
        "A static pointer",
        "A null pointer",
      ],
      correctAnswer: 0,
    },
    {
      id: 23,
      question: "What is a template in C++?",
      options: [
        "A blueprint for creating generic functions or classes",
        "A type of class",
        "A header file",
        "A namespace",
      ],
      correctAnswer: 0,
    },
    {
      id: 24,
      question: "Which operator is used to deallocate memory in C++?",
      options: ["free", "delete", "dealloc", "remove"],
      correctAnswer: 1,
    },
    {
      id: 25,
      question: "What is namespace in C++?",
      options: [
        "A declarative region that provides scope to identifiers",
        "A type of class",
        "A function",
        "A variable",
      ],
      correctAnswer: 0,
    },
  ],
}
